"""FastAPI integration for the GraphQL transport.

Produces a ``strawberry.fastapi.GraphQLRouter`` mounted onto the
existing ``mosaic serve`` app at ``/graphql`` (see
``mosaic.serve.create_default_app`` and the ``mosaic serve --graphql``
flag).

The GraphQL schema is generated once, at mount time, from the
configured client's ``SchemaRegistry``. At request time resolvers use
``request.app.state.hippo_client`` — the exact client the REST routers
read (injected by ``create_default_app`` from the config-driven factory,
issue #42) — so both transports always serve the same deployment.

Mosaic holds zero authn/authz (issue #54 Part A) — ``PassThroughAuthMiddleware``
(``mosaic.core.middleware``) extracts an actor for provenance only, and a
Bridge deployment wraps this transport the same as REST.
"""

from __future__ import annotations

from typing import Any

from fastapi import Request
from strawberry.fastapi import GraphQLRouter

from mosaic.core.client import MosaicClient
from mosaic.core.exceptions import ConfigError
from mosaic.graphql import DEFAULT_MAX_QUERY_DEPTH
from mosaic.graphql.resolvers import build_graphql_schema
from mosaic.graphql.schema_builder import GraphQLTypeBuilder


def create_graphql_router(
    hippo_client: MosaicClient,
    path: str = "",
    graphiql: bool = True,
    max_query_depth: int = DEFAULT_MAX_QUERY_DEPTH,
) -> GraphQLRouter:
    """Build the GraphQL router for one Mosaic deployment.

    Schema generation happens once, here, at startup — resolvers then
    serve every request through the app's shared ``MosaicClient``
    (``app.state.hippo_client``, the same source the REST routers use;
    *hippo_client* is the construction-time registry source and the
    fallback when the app carries no client). The request context
    carries the client, the generated type universe, and a per-request
    DataLoader cache for batched relationship resolution.

    Args:
        hippo_client: SDK client; must carry a ``SchemaRegistry``.
        path: Router-internal path (mount point is chosen by the caller
            via ``app.include_router(..., prefix="/graphql")``).
        graphiql: Serve the GraphiQL IDE on GET requests.
        max_query_depth: Maximum query nesting depth (hardening;
            introspection is exempt).

    Raises:
        ConfigError: When ``hippo_client`` has no schema registry — the
            GraphQL surface is generated from the LinkML schema, so a
            schemaless client cannot be served.
    """
    registry = hippo_client.registry
    if registry is None:
        raise ConfigError(
            "GraphQL transport requires a schema-backed MosaicClient: the "
            "GraphQL schema is autogenerated from the deployment's LinkML "
            "schema. Construct the client with a SchemaRegistry (e.g. via "
            "`mosaic serve --graphql --config mosaic.yaml` with a config "
            "that names a schema_path)."
        )

    builder = GraphQLTypeBuilder(registry).build()
    schema = build_graphql_schema(
        registry, builder=builder, max_query_depth=max_query_depth
    )

    async def context_getter(request: Request) -> dict[str, Any]:
        # Same client source as the REST routers (base.get_client_from_
        # request): the app-state client injected by create_default_app.
        # Falls back to the construction-time client for apps that never
        # set app.state.hippo_client (e.g. a bare include_router mount).
        client = getattr(request.app.state, "hippo_client", None) or hippo_client
        return {
            "client": client,
            "builder": builder,
            "request": request,
        }

    return GraphQLRouter(
        schema,
        path=path,
        graphql_ide="graphiql" if graphiql else None,
        context_getter=context_getter,
        tags=["graphql"],
    )
